package jazzerresults.StudentGrade.reproducers;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
//Crash_ff40169ecb1752457696b723dfa277cd753260d0
public class line34rte {
    static final String base64Bytes = String.join("", "rO0ABXNyABNqYXZhLnV0aWwuQXJyYXlMaXN0eIHSHZnHYZ0DAAFJAARzaXpleHAAAAABdwQAAAABdAgeSjAXMAPAgMCAwIAwMDAwIEZhaWwwMDAwMDAwMDAwTTAwMDAwMDAwMDAwIzAwMDAwf39/f39/MDAwLDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMAoDMDAsMDAwMDAwCgMwFzAwMDAwMDAwMDAsMDAwMDAKFzAwMDB/MDAwMDAwMDAwMDAwMDAwMH9/f39/fzAwMCwwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAKAzAXMDAwMH8wMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIzAwMDAwf39/f39/MDAwLDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMAoDMDDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgCwwMDAwMDAKAzAXMDAwMDAwMDAwMCwwMDAwMAoXMDABwIDAgMCAwIDAgMCAwIAwMH8wMDAwMDAwMDAwMDAwMDAwf39/f39/MDAwLDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwCjADMBcwMDAwMDAwMDAwMDAwMDAjMDAwMDB/f39/f38wMDAsMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwCgMwMCwwMDAwMDAKAzAXMDAwMDAwMDAwMCwwMDAwMAoXMDAwMH8wMDAwMDAwMDAwMDAwMDAwf39/f39/MDAwLDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMAoDMBcwMDAwfzAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAjMDAwMDB/f39/f38wMDAwMDAwTTAwMDAwMDAwMDAwIzAwMDAwf39/f39/MDAwLDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMAoDMDAsMDAwMDAwCgMwFzAwMDAwMDAwMDAsMDAwMDAKFzAwMDB/MDAwMDAwMDAwMDAwMDAwMH9/f39/fzAwMCwwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAKAzAXMDAwMH8wMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIzAwMDAwf39/f39/MDAwLDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMAoDMDDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAMDAsMDAwMDAwCgMwFzAwMDAwMDAwMDAsMDAwMDAKFzAwMDB/MDAwMDAwMDAwMDAwMDAwMH9/f39/fzAwMCwwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAKAzAXMDAwMH8wMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIzAwMDAwf39/f39/MDAwLDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMAoDMDDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgCwwMDAwMDAKAzAXMDAwMDAwMDAwMCwwMDAwMAoXMDAwMH8wMDAwMDAwMDAwMDAwMDAwf39/f39/MDAwLDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwCjADMBcwMDAwMDAwMDAwMDAwMDAjMDAwMDB/f39/f38wMDAsMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwCgMwMCwwMDAwMDAKAzAXMDAwMDAwMDAwMCwwMDAwMAoXMDAwMH8wMDAwMDAwMDAwMDAwMDAwf39/f39/MDAwLDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMAoDMBcwMDAwfzAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAjMDAwMDB/f39/f38wMDAwMDAwTTAwMDAwMDAwMDAwIzAwMDAwf39/f39/MDAwLDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMAoDMDAsMDAwMDAwCgMwFzAwMDAwMDAwMDAsMDAwMDAKFzAwMDB/MDAwMDAwMDAwMDAwMDAwMH9/f39/fzAwMCwwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAKAzAXMDAwMH8wMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCALDAwMDAwMAoDMBcwMDAwMDAwMDAwLDAwMDAwChcwMDAwfzAwMDAwMDAwMDAwMDAwMDB/f39/f38wMDAsMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAKMAMwFzAwMDAwMDAwMDAwMDAwMCMwMDAwMH9/f39/fzAwMCwwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAKAzAwLDAwMDAwMAoDMBcwMDAwMDAwMDAwLDAwMDAwChcwMDAwfzAwMDAwMDAwMDAwMDAwMDB/f39/f38wMDAsMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwCgMwFzAwMDB/MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCMwMDAwMH9/f39/fzAwMCwwMDAwMDAwMDAwMDB4");

    public static void main(String[] args) throws Throwable {
        ClassLoader.getSystemClassLoader().setDefaultAssertionStatus(true);
        try {
            Method fuzzerInitialize = jazzer.JazzerTargetStudentGrade.class.getMethod("fuzzerInitialize");
            fuzzerInitialize.invoke(null);
        } catch (NoSuchMethodException ignored) {
            try {
                Method fuzzerInitialize = jazzer.JazzerTargetStudentGrade.class.getMethod("fuzzerInitialize", String[].class);
                fuzzerInitialize.invoke(null, (Object) args);
            } catch (NoSuchMethodException ignored1) {
            } catch (IllegalAccessException | InvocationTargetException e) {
                e.printStackTrace();
                System.exit(1);
            }
        } catch (IllegalAccessException | InvocationTargetException e) {
            e.printStackTrace();
            System.exit(1);
        }
        com.code_intelligence.jazzer.api.CannedFuzzedDataProvider input = new com.code_intelligence.jazzer.api.CannedFuzzedDataProvider(base64Bytes);
        jazzer.JazzerTargetStudentGrade.fuzzerTestOneInput(input);
    }
}
